### ISSUE TITLE
Does not actually display toasts with the Windows Store version

### ISSUE THREAD

**Issue by marczellm** [aleab/toastify#1]
While the app can now launch the Windows Store version of Spotify Desktop, it does not actually display toasts for it. If I click the blue notification area icon, it says 'Nothing's playing' even though there is something playing.

**Comment by aleab** [comment]
That is odd! :confused:
When I tested it, it worked flawlessy. Tomorrow I'll re-install the Windows Store version and I'll test it again.

**Comment by aleab** [comment]
Did that happen after issue #3, perhaps?
I mean, did you start Toastify, get the *'Please start Spotify manually'* error and then tried to click the blue icon?

If that is the case, then the two issues are related. The only solution, at the moment, is to restart Toastify.
