### ISSUE TITLE
Volumen hotkeys doesent work

### ISSUE THREAD

**Issue by 3tes** [aleab/toastify#102]
If this is a crash, bug or unexpected behaviour report, please use the following template.

## EXPECTED BEHAVIOUR
It should turn the Volumen

## ACTUAL BEHAVIOUR
It does nothing
[Toastify.log](https://github.com/aleab/toastify/files/2742258/Toastify.log)

**Comment by aleab** [comment]
Hi @3tes!
Please, check my answers to issues #50, #69 and #94; in particular, read [this message](https://github.com/aleab/toastify/issues/94#issuecomment-418845888) posted in issue #94.

If none of those answers are able to help you solve your issue, get back with more details.
- Which hotkey is not working (volume up/down or both)? Are the other hotkeys working fine?
- What keys are you specifically using for that/those hotkeys?
- Which volume setting are you using (global or Spotify only)?
- ...

**Comment by 3tes** [comment]
Thank you It helped
