### ISSUE TITLE
Feature request: update Toastify icon to match current Spotify icon

### ISSUE THREAD

**Issue by abcasada** [aleab/toastify#105]
The Toastify icon no longer matches Spotify's icon - the partial circle near the bottom was removed. See screenshot [here](https://imgur.com/a/j7834r5).

**Comment by Vankog** [comment]
Maybe.  
However, from a legal standpoint it it might already be questionable in its current form. Just changing the color is basically not enough to not count as copyright/trademark infringement. So it is better to keep it a bit different to Spotify's current icon to let sleeping dogs lie.

**Comment by abcasada** [comment]
Ah, yes, that's what I wanted. I had seen that option and didn't realize what it was for.

I'm wondering if one of the following would be easier for new users to understand:

(Checked by default) Show Toastify for every new song
(Unchecked by default) Disable Toastify from appearing for every new song

The first explains it to the user the way I personally imagined to be best. The second explains it closer to the way that it seems the dev intended it to be used/understood. I think that either would be clear to users, but the current one is not.

**Comment by abcasada** [comment]
Also, I'm not yet a frequent user of Github; should I modify the issue to my current suggestion/request, or mark it closed and create a new one, or just leave it to have the comment to show my current understanding and suggestion?

**Comment by abcasada** [comment]
Ah, I see, and agree. Thanks for the info.
