### ISSUE TITLE
spotify authorization with facebook 

### ISSUE THREAD

**Issue by Talsaymaree** [aleab/toastify#107]
If this is a crash, bug or unexpected behaviour report, please use the following template.

## EXPECTED BEHAVIOUR
When I click on login with facebook I should be able to log in

## ACTUAL BEHAVIOUR
nothing happens

**Comment by picressant** [comment]
Same problem for me with v1.11.0

**Comment by FruitBWC** [comment]
Same here

**Comment by aleab** [comment]
This should be fixed in [v1.11.1](https://github.com/aleab/toastify/releases/tag/v1.11.1). Apologies for the buggy release.
