### ISSUE TITLE
Spotify Authorization Script Error

### ISSUE THREAD

**Issue by bahari15** [aleab/toastify#109]
I just finished updating to the new version of toastify, and always got this particular error during the authorization.
I'm using windows 8.1 and FYI the album cover still doesn't show up on my toast notifications.

![screenshot 353](https://user-images.githubusercontent.com/36342630/52896445-9309f880-31fa-11e9-8fa4-0b98eab58833.png)

**Comment by bahari15** [comment]
And apparently because of this error my toastify is no longer working, despite me playing various songs toastify always shows that "nothing is playing."

**Comment by aleab** [comment]
This should be fixed in [v1.11.1](https://github.com/aleab/toastify/releases/tag/v1.11.1). Apologies for the buggy release.
