### ISSUE TITLE
Interference with XAMPP

### ISSUE THREAD

**Issue by mikedorst** [aleab/toastify#115]
With the latest update toastify now interferes with XAMPP.

If you don't know XAMPP, it's a program to let programmers develop websites in localhost, it provides an apache and mysql server. Whenever I have toastify open I am no longer able to access localhost pages but as soon as I turn it off it works again.

XAMPP uses the following ports by default:

![image](https://user-images.githubusercontent.com/27761242/53325217-11ddf000-38e3-11e9-96c5-9b1a8c43d3b1.png)

I didn't see an option to change ports in Toastify and have no idea what's causing the issue or how to resolve it.

## EXPECTED BEHAVIOUR
Localhost and XAMPP to work alongside each other

## ACTUAL BEHAVIOUR
Localhost stops working as soon as toastify opens

## STEPS TO REPRODUCE THE BEHAVIOUR
1. Install [xampp ](https://www.apachefriends.org/index.html) I use the latest version of php.
2. Turn xampp on
3. Have a file in htdocs that you can open.
4. Turn toastify on and see it not work.
5. Turn toastify off and see it work again

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/2899636/Toastify.log)

**Comment by mikedorst** [comment]
Somehow seems to work after an hour or so. Not sure what was wrong.

**Comment by aleab** [comment]
This will be fixed in the next release.
