### ISSUE TITLE
bug: dropshadow not applying correctly

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#14]
Playing with the dropshadow, there seems something off.
It started with this setting:
![ds1](https://user-images.githubusercontent.com/3804909/30514390-26de2808-9b14-11e7-8170-5f94e82d051d.png)
seems legit and valid.

Then I activated the bottom shadow, but let both parameters at 0.
This resulted in the weird effect that the top title lost it shadow as well. The bottom still had none. This was reversible and repeatable.

Then I set the bottom parameters, but this led to the effect that the top has always shadow and the bottom has always none, no matter what other selections I made afterwards:
![ds2](https://user-images.githubusercontent.com/3804909/30514427-bf318852-9b14-11e7-8217-b1693ebf03b1.png)
![ds3](https://user-images.githubusercontent.com/3804909/30514429-bf340b90-9b14-11e7-81fb-8f623a9ec8c9.png)
![ds4](https://user-images.githubusercontent.com/3804909/30514428-bf334818-9b14-11e7-9c68-08f252b3a2f0.png)

I reset to defaults and restarted.
Changed the top, bottom and border alpha. saved.

Then I disabled the top shadow, with no effect:
![ds5](https://user-images.githubusercontent.com/3804909/30514484-8516ef26-9b15-11e7-887c-b609aa06b413.png)
set enabled the bottom shadow with this effect again, like above:
![ds6](https://user-images.githubusercontent.com/3804909/30514489-bd90bba2-9b15-11e7-8bb1-77d10d479c4e.png)
enabled top shadow:
![ds7](https://user-images.githubusercontent.com/3804909/30514496-dabefde2-9b15-11e7-87f6-bb70775b0ea0.png)
entering bottom parameters brought back the top shadow:
![ds8](https://user-images.githubusercontent.com/3804909/30514498-f52adade-9b15-11e7-9cbd-d02e815b866c.png)

and so on... ^^

there seem to be some minor mix-ups ;-)

**Comment by aleab** [comment]
Ahahah, I'm an idiot. 🤦‍♂️ 
This is what I've done, basically:
```
if (settings.ToastTitle1DropShadow)
{
    this.Title1.Effect = new DropShadowEffect
    {
        ShadowDepth = settings.ToastTitle1ShadowDepth,
        BlurRadius = settings.ToastTitle1ShadowBlur
    };
}
if (settings.ToastTitle2DropShadow)
{
    this.Title1.Effect = new DropShadowEffect
    {
        ShadowDepth = settings.ToastTitle2ShadowDepth,
        BlurRadius = settings.ToastTitle2ShadowBlur
    };
}
```
Damn copy-paste!!
I'm just releasing a v1.9.8.

**Comment by Vankog** [comment]
hehe, nice one! happens to me, too.

**Comment by aleab** [comment]
New version is ready.

**Comment by aleab** [comment]
Thanks for all your feedback, it's really appreciated. 👍

**Comment by Vankog** [comment]
alright, it seems there is still something off.

reset the color&font settings and reduced alpha to see the shadow:
![ds1](https://user-images.githubusercontent.com/3804909/30514982-38cacfce-9b20-11e7-90b1-aced52b6a65e.png)
disabling top shadow has no effect:
![ds2](https://user-images.githubusercontent.com/3804909/30514986-599befd0-9b20-11e7-8653-537e35a7a719.png)
 enabling bottom shadow, neither:
![d3](https://user-images.githubusercontent.com/3804909/30514995-83cc270c-9b20-11e7-9dd8-a53a9fc165d1.png)
ah, but this might be only because of the missing parameters. changing the bottom parameters works:
![ds4](https://user-images.githubusercontent.com/3804909/30515004-b1f6fe7c-9b20-11e7-9989-0c20ee896eba.png)
But the top shadow and parameters still don't work yet:
![ds5](https://user-images.githubusercontent.com/3804909/30515011-d84bdef8-9b20-11e7-84e9-1fcb5904cc44.png)


So, still something odd.


another thing:
Could you set some default bottom parameters? The zeroes are a bit deceiving, because nothing happens when the bottom shadow gets activated. (see above in my process)

and lastly a side note:
When resetting to default (e.g. in `Colors & Font`), the current form values still show the old values until the window gets reopened. (e.g. color alpha)

**Comment by aleab** [comment]
These latest commits are full of dumb errors, geez! 🤦‍♂️ 

I forgot to remove the old, static shadow that was set in the .xaml file. Also, I forgot to set those depth and blur values to zero if the DropShadow boolean is false.

I've set some default values for the bottom shadow.

Try downloading version 1.9.8 again.

**Comment by aleab** [comment]
For your side note, can I ask you to open a new issue, please? (I just need it as a reminder)

I actually pretty much never changed the *set to default* functionality since I forked the original project, so I don't really know what it does. I'll have a look at it *soon*.
However, I'm pretty sure it resets everything, and not just the settings of the current tab.
The fact that the values in the form don't get refreshed is probably caused by the fact that the window doesn't receive any notification of that event – I'm not sure though.

I'll let you know.

**Comment by Vankog** [comment]
now it works :-)
![ds1](https://user-images.githubusercontent.com/3804909/30516051-4b9dce8a-9b34-11e7-9ce5-272fa996a5b6.png)
