### ISSUE TITLE
Upgrade from fork to v1.9.8 results in exception in log.

### ISSUE THREAD

**Issue by ryantheleach** [aleab/toastify#16]
Updating from nachmore/toastify to v1.9.8 results in the following log when trying to launch.

2017-10-09 15:33:24  -  Value cannot be null.
Parameter name: input
2017-10-09 15:33:47  -  Value cannot be null.
Parameter name: input
2017-10-09 15:33:58  -  Value cannot be null.
Parameter name: input
2017-10-09 15:34:36  -  Value cannot be null.
Parameter name: input
2017-10-09 15:34:50  -  Value cannot be null.
Parameter name: input
2017-10-09 15:35:05  -  Value cannot be null.
Parameter name: input

[Toastify.xml.txt](https://github.com/aleab/toastify/files/1367548/Toastify.xml.txt)

Deleting this configuration and restoring the default did not fix it.

**Edit:** Downgrading to 1.9.6 worked, thanks.

**Comment by aleab** [comment]
Downgrading is not really a solution.
What happened exactly? Any error message?

**Comment by ryantheleach** [comment]
No error messages, never appeared in tray, never launched. All I had was the log.

Windows 10 FYI. not sure if you need any other environmental info.

**Comment by aleab** [comment]
Ok, I got it. It just crashes without messages.
I'll do some tests and let you know when it's fixed.

**Comment by aleab** [comment]
The [new release](https://github.com/aleab/toastify/releases/latest) should work fine now.
Thanks for the issue report, Ryan.
