### ISSUE TITLE
Hotkey assignment is not reset properly when hitting default.

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#18]
v. 1.10.
Steps:
1. Set up some hotkeys and save.
1. hit default.
1. set up the same hotkeys again:
    -> 1. bug: a warning: key combinations are already used
1. change a hotkey to another key-combination and save:
    -> this key combination can be set fine
1. change the same hotkey back to the previous key combination and save:
    -> 2. bug: hotkey still cannot be set, even though another key combination was set intermittently.

workaround:
- restart Toastify and everything works fine.

**Comment by aleab** [comment]
I have had a hard time understanding how the hotkeys system was designed. I guess I didn't understand it correctly. Probably the hotkeys don't get unassigned/unregistered from the system for some reason.

Does the same thing happen when using the *default all* option?

**Comment by Vankog** [comment]
Guess what: ^^
...
...
...
...
...
...
...
...
...
"default all" does not reset hotkeys at all ^^

(btw: clicking on "default all" has no visual clicking feedback. i.e. The dropdown stays open and no visual indicator show whether the action took place. Not sure if this is worth opening another issue.)

**Comment by aleab** [comment]
> "default all" does not reset hotkeys at all ^^

Holy shit! The error is just an *if* and a wrong boolean argument, I think.

> Not sure if this is worth opening another issue.

It's not. This is enough. 😃

**Comment by Vankog** [comment]
Wow, this looks like it was just a tiny bit more than just "an *if* and a wrong boolean argument" ^^

**Comment by aleab** [comment]
Kinda! 😅
