### ISSUE TITLE
Show live preview of Toast layout

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#19]
I have another wish:
When changing the layout and colors of the Toast, the preview does not show the changed settings until saved. A live preview would be awesome.
This has two reasons:
1. The save button loses its value when you have to save anyway to preview any change, because you cannot return to the previous settings anymore.
1. It is cumbersome to hit save all the time when you are just playing around with the layout.

Save should only be clicked if the user really wants to save.

**Comment by aleab** [comment]
Fair enough. Valid points. :+1:
