### ISSUE TITLE
Gentler way to terminate Spotify?

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#23]
Is there a gentler way to kill Spotiy when quitting Toastify?
It seems Spotify enters panic mode when Toastify terminates it, which I infer from two facts:
1. Spotify's window dimensions and location are reset everytime Toastify closes Spotify. They stay the same when closing Spotify manually, though.
1. In ProcessExplorer I saw once by chance that while termination was in process, another process was launched inside the Spotify tree shortly that strikingly looked like a diagnostics tool, based on the icon and the name of the process (which I cannot recollect unfortunately).  
I tried to reproduce this by using Process Monitor, but it did not show up.

**Comment by aleab** [comment]
To be honest, I didn't mess too much with the code that handles termination; it's almost the same as it was in the original repository, except some refactoring.
I'm almost sure, however, that sometimes Spotify is closed forcefully.

I'll take a look and report back soon™.

**Comment by Vankog** [comment]
Take your time® ;-)

**Comment by Vankog** [comment]
That's interesting. You basically click through Spotify's menu, right? Does this also work when Spotify is minimized and/or in tray?

**Comment by aleab** [comment]
Slightly incorrect. I'm not clicking or generating click events, but rather sending to Spotify's window the same messages it would receive if you clicked on the menu item.
Sending mouse clicks would require the window to be on top; these simple messages, on the other end, only require the window to actually exist. So, yeah... It works when Spotify if minimized or in the tray as well.

**Comment by aleab** [comment]
Unfortunately, since the latest release of Spotify (v1.0.75.483.g7ff4a0dc) it's not possible to gently terminate its process anymore.

See 9cb83d1 and the referenced issue for details.
