### ISSUE TITLE
Bug: when playing another title after pause, toast still shows the old title

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#24]
got a special gift for you. a christmas holiday bug! yay!!!^^

Version: your custom build from the performance issue.

Steps:
1. config: toast shows up automatically
1. Start a track (to be sure, in a playlist)
1. pause the track
1. play a new track either by directly starting it or skipping the title in any direction  
-> result: The old title still shows up as playing

**Comment by aleab** [comment]
The 🎁🐛 is appreciated! 😜 

I managed to reproduce the issue with that custom build. However, (fortunately?) I couldn't reproduce it with my local version. Some changes not yet committed and pushed might have fixed it.

**Comment by Vankog** [comment]
fine, that settles it then :-)
