### ISSUE TITLE
Doesn't seem to work with the Windows/Microsoft Store version of Spotify

### ISSUE THREAD

**Issue by thewan056** [aleab/toastify#26]
OS: Windows 10 Pro 1709
Spotify: 1.70.388.0 via Microsoft Store
Toastify: 1.10.0

Awesome project. Saw that it supports the Microsoft Store version and tried it straightaway. Stuck at "waiting for Spotify" even though Spotify launches. Got timeout error dialog after waiting a while. Is there anything that I maybe doing wrong?

https://vgy.me/rFDfRe.png

**Comment by aleab** [comment]
Was Spotify already running when you started Toastify? If it wasn't, try starting Spotify first and then Toastify.

Normally, it shouldn't really matter what you start first, but sometimes, if Spotify takes too long to load (more than a minute, IIRC), Toastify times out and gives that error dialog.

**Comment by aleab** [comment]
You can also try out this test version ([ToastifyInstaller.zip](https://github.com/aleab/toastify/files/1598031/ToastifyInstaller.zip)) with the most recent changes.
If this test version times out as well, look for any log file inside *%LocalAppData%\Toastify* and let me know.

**Comment by aleab** [comment]
@thewan056, any news?

**Comment by aleab** [comment]
**Closed for inactivity.**

I couldn't reproduce the issue and without further details it's impossible to track down the actual issue.

@thewan056, if you are still getting that error or if it happens again, you are free to comment here and I will re-open this issue.

**Comment by computerwizjared** [comment]
For anyone encountering this issue in the future, I discovered that Toastify was having trouble accessing the domain "open.spotify.com" due to a filter in place. Make sure you don't have something, whether DNS, a firewall, or a web filter blocking Spotify, and you should be good 👍
