### ISSUE TITLE
Multiple screens

### ISSUE THREAD

**Issue by Jabbl** [aleab/toastify#28]
When changing toast position; if I move it to my second screen, placed to the left of my main one, an error occurs and the toast moves to default position.
If I then try to open the settings, another error occurs, as the program saves a negative value to x-pos, and then refuses to open.
Fixing this requires opening the xml-file and manually resetting the value.

Would be nice if I could place the toast in my second screen, as it's mostly for stuff like that to begin with

**Comment by aleab** [comment]
I'll try to look into this issue soon enough. It might take some time, though, since I currently do not have a second monitor to test it with.

**Comment by aleab** [comment]
Sorry for the late fix. Multi-screen configurations should be supported in the new version now.
