### ISSUE TITLE
Error message on startup

### ISSUE THREAD

**Issue by marczellm** [aleab/toastify#3]
Even though the app successfully starts the Windows Store version of Spotify Desktop, an error message appears saying

> An unknown error occurred when trying to start Spotify. Please start Spotify manually.
Technical details: Object reference not set to an instance of an object.

**Comment by aleab** [comment]
Thanks for the feedback marczellm!
I already encountered that error; it also affects the desktop version of Spotify, unfortunately.
Tomorrow I'll look into it.

A temporary solution is to start Spotify manually first and then start Toastify.

**Comment by aleab** [comment]
A new release with the fixes is now available [here](https://github.com/aleab/toastify/releases/latest).

If you encounter other errors or have suggestions to improve this application, feel free to open other issues.
