### ISSUE TITLE
Remove modifier requirement on hotkeys

### ISSUE THREAD

**Issue by Blazeflack** [aleab/toastify#32]
Hi.

I have been using the original version of Toastify for a long time. A few days ago the original version stopped responding to hotkeys, so I went looking for solutions and came across this repository. I had no idea you had picked up the torch to continue its development. I'm extremely happy about that, so thanks.

**Here is my issue:**
Previously I would mainly use Toastify to have an easy way to control the volume of Spotify. I would do that by assigning buttons on my mouse to the VolumeUp and VolumeDown media keys. I would then use those hotkeys in Toastify to increase or decrease the volume which worked just fine.

Your version has introduced a requirement of using at least one modifier though, which prevents me from doing what I have been doing so far. I don't understand the need to enforce this requirement. Would it be possible to lift it so people are free to decide if they want to use modifiers or not?

Thank you for your consideration.

**Comment by aleab** [comment]
Hi @Blazeflack!
You are indeed right, that requirement is really unnecessary. It'll be removed in the next version.

Regarding assigning mouse buttons to actions – was it possible to do that in the original project? By a quick look at the code, it shouldn't be (neither in my version of Toastify nor the original).

**Comment by Blazeflack** [comment]
Hi @aleab 

That sounds great, thank you.

Sorry about the confusion, I do indeed use Razer Synapse. It doesn't allow me to use a modifier when assigning a media key function to a button, otherwise I wouldn't mind the requirement in Toastify.

Thank you.

**Comment by aleab** [comment]
Modifier requirement has been removed in [v1.10.3](https://github.com/aleab/toastify/releases/tag/v1.10.3).
