### ISSUE TITLE
Latest release is unable to connect to spotify

### ISSUE THREAD

**Issue by stoopdapoop** [aleab/toastify#33]
It looks like this is a known bug that has been fixed recently, but none of the releases include the fix, is there a plan to create a new release with an installer in the near future?

**Comment by aleab** [comment]
Hi @stoopdapoop.
What fixed known bug are you referring to exactly? Are you getting an error message at startup? Can I have a look at your log file in that case? (Log files are in *"%LocalAppData%\Toastify"*; e.g. *"C:\Users\\{UserName}\AppData\Local\Toastify\Toastify.log"*)

I've got a new release planned for this week, hopefully.

**Comment by stoopdapoop** [comment]
I'm referring to bug 31. https://github.com/aleab/toastify/issues/31

looks like I was mistaken about it being fixed though.

I can get you the log when I get home tonight.
