### ISSUE TITLE
Changing FadeOut Time not working.

### ISSUE THREAD

**Issue by F1rrel** [aleab/toastify#38]
## EXPECTED BEHAVIOUR
Changing FadeOut Time of Toast.

## ACTUAL BEHAVIOUR
Unhandled exception: Object reference not set to an instance of an object.

## STEPS TO REPRODUCE THE BEHAVIOUR
Delete one number in FadeOut Time input window.

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/1796112/Toastify.log)

**Comment by aleab** [comment]
@F1rrel, thanks! I'll work on it.

**Comment by aleab** [comment]
Hi @F1rrel!
Since this issue seems to be similiar to #37, I'll just repeat what I said there.

Can you try [this](https://github.com/aleab/toastify/files/1797890/ToastifyInstaller.zip) test version and report back with the new log file **and** with the content of the _"C:\Users\\{UserName}\AppData\\**Roaming**\Toastify"_ directory?
You can either upload each file separately (there should be maximum 3 files in total) or compress them in a zip file. Whatever you like the most.

**Comment by F1rrel** [comment]
Hi @aleab,
I have tried to install the test version, but I am getting an error: 
System Windows can't get access to the device, file or path. Maybe you don't have the permissions to access this subject. (translated from the Slovak language)
I have run it as an administrator, so I should have the appropriate rights to it.

C:\Users\{UserName}\AppData\Roaming\Toastify
[Toastify.xml.zip](https://github.com/aleab/toastify/files/1798224/Toastify.xml.zip)

**Comment by aleab** [comment]
Can you upload you log file as well? It's in _"C:\Users\\{UserName}\AppData\\**Local**\Toastify"_.

That error message is really strange, because Toastify doens't require admin rights at all. Have you tried to **not** run it as administrator, but rather as normal user?

**Comment by F1rrel** [comment]
Running it as admin/normal user and changing compatibility did not help.

Here is the log file: 
[Toastify.zip](https://github.com/aleab/toastify/files/1798289/Toastify.zip)

**Comment by aleab** [comment]
I might have misunderstood your previous message. Did the *"System Windows can't get access to the device, file or path... "* error message came up after installing the test version (when you launched Toastify) or during the installation?

Also, it seems like Toastify couldn't reach Spotify's servers for some reason. Are you using Windows' *hosts* file to block (\**cough\**) Spotify's ads? Or perhaps is your firewall doing that?
If you are, you can continue to do that, but you have to remove *"open.spotify.com"* from the blocked hosts.
If you don't know, you can see if that's the issue by launching the command prompt (WindowsKey+R, type *cmd* and hit enter), and then the following command (you can post a screenshot of the results here afterwards, if necessary):
```batch
ping -n 5 open.spotify.com
```

**Comment by F1rrel** [comment]
Sorry, because of the message at the end of installation I suspected that the installation failed, but the toastify was installed and was running. But I could not open toastify settings for some reason.
Today after restarting the PC, I installed again the test version and tried to modify the fade time (did not work), so I am including the needed files.
[Toastify.zip](https://github.com/aleab/toastify/files/1799269/Toastify.zip)
I use the power of money to remove ads from spotify and today pinging spotify server was working fine.

**Comment by aleab** [comment]
Thanks for the files. I'll try to replicate your issue and fix it ASAP.

**Comment by aleab** [comment]
Fixed it in the latest commit!
I'll release a new version soon™.

**Comment by aleab** [comment]
New version has been released: [v1.10.4](https://github.com/aleab/toastify/releases/tag/v1.10.4)
