### ISSUE TITLE
Toastify fails to start

### ISSUE THREAD

**Issue by smur89** [aleab/toastify#41]
Latest version of Toastify, to fix issue with the latest version of Spotify, doesnt work with my system. Dies on startup. I am running behind a corporate proxy.

## EXPECTED BEHAVIOUR
App should start up

## ACTUAL BEHAVIOUR
![image](https://user-images.githubusercontent.com/2413634/37205663-84480264-238d-11e8-9574-5f413e2edf50.png)

## STEPS TO REPRODUCE THE BEHAVIOUR
- Download the Toastify installer from https://github.com/aleab/toastify/releases/download/v1.10.3/ToastifyInstaller.exe
- Install Toastify
- Run Toastify

## LOG FILE
https://pastebin.com/UfmYgFV5

**Comment by aleab** [comment]
PR #40 will most likely fix it

**Comment by smur89** [comment]
Great, thanks!

**Comment by aleab** [comment]
Hi @smur89. The mentioned pull request has been merged into the master branch yesterday.
I haven't yet released an official build, but in the meantime if you happen to be behind that corporate proxy again before I release it, you can use [this](https://github.com/aleab/toastify/files/1799542/ToastifyInstaller.zip) test build and see if it fixes your issue.

**Comment by aleab** [comment]
New version has been released: [v1.10.4](https://github.com/aleab/toastify/releases/tag/v1.10.4)

**Comment by smur89** [comment]
Hey @aleab, sorry for not getting back to test, I'm just setting up Toastify again now on v1.10.8.

Working great for me now. Would be great to be able to specify a DNS name for the proxy as well as the IP, that got me for a while, but all good now. Thanks for everything

Cheers
