### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by ersanqi** [aleab/toastify#42]
Hi, how do I run the installation? I don't see any file that installs in one-click, from the downloaded zip file. Apologies for the newbie question, first time here.

**Comment by aleab** [comment]
No worries!
Go [here](https://github.com/aleab/toastify/releases/latest) (this link will always point to the latest release) and download *ToastifyInstaller.exe*.

**Comment by ersanqi** [comment]
Thank you so much for your kindness and link, also the quick reply! Works (:

**Comment by Vankog** [comment]
hey, @ersanqi 
Here is a tip for you.
You can find the current releases (incl. setup files) of Github projects usually at this point:
![releases](https://user-images.githubusercontent.com/3804909/37254173-0a7aa798-253b-11e8-9284-ce635224bba2.png)

Hope this helps!
