### ISSUE TITLE
Volume controls only affect Spotify

### ISSUE THREAD

**Issue by hardcorehead87** [aleab/toastify#5]
In the last release we have to following features added;
- Added an option to use Spotify's volume control instead of the Windows volume mixer
- When using the Windows volume mixer, the volume increment can now be customized.

One of these features affected how the windows mixer volume is handled though.
Where before system volume would change, now only the spotify application volume is affected.
While on the one hand this is logical, I liked the fact that the volume controls affectect system volume.
This triggered the windows volume pop-up to see the current volume (top of screenshot).

![image](https://user-images.githubusercontent.com/5999142/28017618-558b53ee-657a-11e7-87b0-5ca49369d68d.png)

**Comment by aleab** [comment]
Yeah, I can see why someone would want/prefer that. I don't know why I didn't metion it in the changelog though.
Anyway, that option will be back in the next release.
Thanks for the feedback.

**Comment by hardcorehead87** [comment]
Great. Thanks for keeping this project going.

**Comment by aleab** [comment]
Version [1.9.5](https://github.com/aleab/toastify/releases/latest) is released.

**Comment by hardcorehead87** [comment]
Thanks. Much appreciated ;-)
