### ISSUE TITLE
Volume Up/Down doesn't work

### ISSUE THREAD

**Issue by seiffs** [aleab/toastify#50]
After the March 2018 Spotify update the old Toastify stopped working. So I upgraded to this fork version 1.10.4. Most shortcuts like pause/play/next/prev started working, but Volume up/down still don't work.

## EXPECTED BEHAVIOUR
Mapped hotkeys for Volume Up/Down should modify the sound volume.

## ACTUAL BEHAVIOUR
Nothing happens when pressing those hotkeys

## STEPS TO REPRODUCE THE BEHAVIOUR
Map Volume Up/Down, apply and try the key press.

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/1813201/Toastify.log)

**Comment by aleab** [comment]
Hi @seiffs! Thanks for the bug report.

Just a couple of questions.
1. What *"Volume control mode"* option are you using in Toastify? *Global* or *Spotify*?
2. Do you have any software running that could interfere with media keys (maybe other media players) or that could be messing with Windows volume objects, i.e. the Mixer (maybe something like VoiceMeteer)?

**Comment by seiffs** [comment]
Hi,
I didn't notice there is an option to switch the _Volume control mode_. There was _Spotify_ and after switching it to _Global_ it started working.

So it's not a bug. Thank you for the suggestion.

**Comment by aleab** [comment]
It should be working in either case, though. The *"Global"* option changes the global volume in the Windows Volume Mixer, while the *"Spotify"* option only changes Spotify's volume in the Volume Mixer.

Glad it's resolved! 😄

**Comment by aleab** [comment]
@BattleNachos, thanks for the heads-up, that will surely help someone with the same issue in the future.

I might also add that probably (I'm not sure) having softwares like Voicemeeter installed, or however something that *messes* with the Mixer's objects, might give unexpected results.

**Comment by GarryPlays** [comment]
OMG! thanks for that. I think the preset changed or something. At least it stopped working for me.
But yes, it was set to Spotify, doesn't do a thing for me, global works now great as before (didn't know that feature was there)
Windows 10 home, no other keygrabber installed

**Comment by collinrich** [comment]
I have the Volume control mode on Spotify only, and I want the toastify volume hotkeys to only affect Spotify's volume. ei. I'm playing a game and I want to increase/decrease Spotify volume without it changing my game volume. However, these hotkeys don't seem to work for Spotify volume only. Any suggestions?

**Comment by mat1324** [comment]
I had the same problem but then i changed the hotkeys to shift up and down for the the volume then reset both apps, after that it worked fine, hope this helps :)

**Comment by CoolDudeGaming** [comment]
> I had the same problem but then i changed the hotkeys to shift up and down for the the volume then reset both apps, after that it worked fine, hope this helps :)

Tried this too and my volume for spotify only still doesnt work, all the other hotkeys work great
