### ISSUE TITLE
Toast fade-out time 

### ISSUE THREAD

**Issue by gurkburk76** [aleab/toastify#51]
I expected to be able to set the time for the fade-out time for toast below 1000 msec, can't go lower than 1000 atm.

**Comment by gurkburk76** [comment]
I was able to have it sub-1000msec on versions prior to 10.4, unsure if this behaviour of not beign able to go below 100msec was introduced in this forked version that works with spotify 1.0.75.483.g7ff4a0dc

**Comment by gurkburk76** [comment]
Seem like the change needed would be here:

src/Model/Settings.cs

public void SetDefaultToastGeneral()

 this.FadeOutTime = new SettingValue<int>(DefaultValueOf(this.FadeOutTime, nameof(this.FadeOutTime)), new Range<int>(1000, int.MaxValue));

change 1000 to .. well 1 or something :)
Next time you release, please adjust.

**Comment by aleab** [comment]
What's the point of having the toast show up for 1ms or even anything below 1s? Just disable it.
I'm curious, what are you using the toast for? I think it's biologically impossible to read its content in less than a second.

**Comment by gurkburk76** [comment]
I ususally like to use 500ms or so, below 1ms would be stupid, but below 1000ms pretty resonable i think.

**Comment by aleab** [comment]
Reduced the minimum allowed value to 100ms. Values lower than that caused some visual glitches sometimes.

The next version will come out as soon as the major bugs and requests reported in the current version are fixed.

**Comment by Vankog** [comment]
@aleab I think you confused fade-out time with on-screen time, did you? ;-)

**Comment by aleab** [comment]
@Vankog What makes you think so? 😕

**Comment by Vankog** [comment]
because of:
> What's the point of having the toast show up for 1ms or even anything below 1s?

You are talking about the fade-out time as of the time the toast is visible.

**Comment by aleab** [comment]
Exactly! 😕
The fade-out time is not the duration of the fade-out animation (which is fixed to 500ms), but rather the time span T after the fade-in animation during which the toast remains visible.

I concur that *"Visibility duration"* might have been a better label for it, but I think I just stick to what nachmore used before me.
