### ISSUE TITLE
Toastify saving bug?

### ISSUE THREAD

**Issue by clarkycal** [aleab/toastify#52]
Hello,
In the current release, saving doesn't seem to work (For me at least), I had given toastify.exe application access within my Anti-Virus, still, doesnt work.

Here is a video I created to show many examples: https://youtu.be/98yVi-iV9wM
To summerise, say I was to tick 'Launch toastify on windows' and then hit 'save', then restart the program it will not remember what I had chosen after saving.

Here are my last 2 logs.

[Toastify.log](https://github.com/aleab/toastify/files/1821739/Toastify.log)

[Toastify2018-03-16.log](https://github.com/aleab/toastify/files/1821742/Toastify2018-03-16.log)

**Comment by aleab** [comment]
Hi @clarkycal.

You are indeed right! Hotkeys and *"Launch toastify on windows"* settings are not saved or loaded correctly for some reason.

I'll investigate right away.

**Comment by Tumpo** [comment]
I just came here to tell this and only to see that fixing has started 12 minutes ago. Awesome job!

**Comment by aleab** [comment]
Fixed it! I have no ETA for the next release, though. I still have to fix a couple more things.

**Comment by aleab** [comment]
Fixed in new version [v1.10.6](https://github.com/aleab/toastify/releases/tag/v1.10.6)!
