### ISSUE TITLE
please sign the installer

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#6]
Hey there. Nice to see further development on Toastify over here.
A minor issue I came across:
The Win 10 security system actively prevents the installer from executing by default, because it is from an unknown vendor/publisher/whatever. 
I think users who don't know how to deal with this will be repelled by this. Especially, because the option to run the program nonetheless is a bit hidden.

Could you have a look into this? Not sure what is needed for Windows to permit it, but I think providing a Vendor name might be a start.

**Comment by aleab** [comment]
Unfortunately, AFAIK, I cannot provide a "Vendor name"; that information should come from a certificate signed by a trusted CA.
I am definitely not going to pay for a certificate and I do not know of any free CA (if you do, let me know). I could try with a self-signed one, but I doubt Windows will fall for that. ;)

The UAC warning only pops up with the installer, right?
If that is the case, I might consider to distribute the app without the installer.

**Comment by Vankog** [comment]
Yes, it only occurred with the installer.

Yeah, I don't expect you to pay for a certificate. Just did a short research and found that you indeed need a "code signing certificate". However, it seems over the past few years all free certification services known dropped the free tier. Couldn't find a suitable free one with a quick search. CAcert might be one, but they are generally not included as trusted root in the system. So it is as good as a self-certificate from a user perspective. Meaning: There is no reason to do this.

This is quite annoying. In Windows before 10 the UAC was still user friendly. Now the UAC just hides the possibility to install unsigned programs as best as it can.

**Comment by aleab** [comment]
Yeah, the *great minds* at Microsoft did a really good job in hiding it. :trollface:

Anyway, can you please try [this](https://github.com/aleab/toastify/releases/download/v1.9.5/ToastifyInstaller.zip) and see if the warning still appears? It's just the installer inside a zip.
I've done some research and it seems that the blue UAC warning (actually, it is a SmartScreen warning) only appears with files downloaded from the web that have an unknown publisher. Basically, when you download a file, Windows adds a flag to it; however, if the file is inside a zip it should not be flagged.

**Comment by Vankog** [comment]
Well, it seems there is also something else at play.
I tried both, the setup I downloaded lately and your archived one, again and this time only the usual UAC-warning popped up, asking me whether I'm sure. The SmartScreen blockage did not appear this time. 

I figure that SmartScreen synchronized its database of known executable fingerprints and now recognizes the installer. (EDIT: Or it remembered that I allowed it in the first place... Also a valid possibility. hmm...)
Windows Defender has this option to block, warn or allow "unknown apps and programs from the internet". So it might be your installer builds just need some time and user-accepted and probably a dedicated scan by microsoft/windows to count as "known". 

So, I figure, if you'd create a new build right now, the SmartScreen filter would come up again. I can test this new build out as the zip-version if you like.

**Comment by Vankog** [comment]
Never mind. I just tried it with an older version.
As I suspected, the SmartScreen came up again.

And as you suspected, it does not come up when using the archived version. HOWEVER, this only works for temp files (double clicking), not if you unzip the archive. 

So I have an idea. Why not utilizing a self-extracting rar archive that unpacks itself to the temp folder and runs the setup automatically. There are quite some programs out there that use this method.

**Comment by aleab** [comment]
That sounds like a good idea! 👍
I'll look into it tomorrow and I'll let you know.

**Comment by aleab** [comment]
[Here](https://github.com/aleab/toastify/releases/download/v1.9.5/SFXToastifyInstaller.exe) is the self-extracting archive. Let me know if it works.

**Comment by Vankog** [comment]
I can't test this particular version, because windows already knows the 1.9.5 installer inside, so the smart screen would not come up nonetheless.
Could you pack an old version for test purposes? For example the 1.9.2 installer is still unknown to my system.

**Comment by Vankog** [comment]
Wow, tested it nonetheless and have experienced a quite peculiar behaviour...
The first time it worked just fine. SmartScreen did not come up and the installer started up. Closed it und opened it again and surprisingly SmartScreen came up this time.

Cleared temp files, downloaded the file again just to be sure and renamed it.
But SmartScreen keeps popping up. Totally bonkers behaviour if you ask me.

**Comment by aleab** [comment]
It unpacks everything in a randomly named directory inside the temp folder; however, it gets removed when the installation process ends. The directory name always starts with *"7z"*.

**Comment by aleab** [comment]
Could it be the self-extracting archive that triggers SmartScreen?
I've modified it to include a dialog window before running the installer.
Can you try it again?

**Comment by aleab** [comment]
FYI, I'm using the [7zS SFX module](https://sevenzip.osdn.jp/chm/cmdline/switches/sfx.htm) to generate the self-extracting archive.

**Comment by Vankog** [comment]
Yes, the SFX itself triggers SmartScreen, including the new version.
But it is strange that this only happened after the very first run went without a SmartScreen interruption. It's like Windows realized too late that there was something to block. ^^

I tried it myself, but with WinRAR and it seems this works. Here the Setup:
Create an archive of the setup file with following options:
![sfx1](https://user-images.githubusercontent.com/3804909/28927940-2e6a0b52-786c-11e7-93d9-a26879fad718.png)
![sfx2](https://user-images.githubusercontent.com/3804909/28927947-33ae9a88-786c-11e7-982e-3d66be22d301.png)
![sfx3](https://user-images.githubusercontent.com/3804909/28927954-385b99fa-786c-11e7-8c26-5c33e3a3c444.png)
![sfx4](https://user-images.githubusercontent.com/3804909/28927960-3c7bb984-786c-11e7-8d4d-304e3dfe72e4.png)
![sfx5](https://user-images.githubusercontent.com/3804909/28927963-4010c7b0-786c-11e7-8ce2-1829311af89f.png)

When I trigger the SFX only the UAC comes up, but not the SmartScreen. So it seems it works. But its a few KB bigger than the 7zip version.

**Comment by aleab** [comment]
Ok. Just to be sure, try with the new file I've uploaded ([here](https://github.com/aleab/toastify/releases/download/v1.9.5/SFXToastifyInstaller.exe)).

However, even if this works, I'm not completely sure I want to use WinRAR; I'd prefer a totally free/redistributable software.

**Comment by Vankog** [comment]
Oh boy... it did NOT work... 
Well, I guess my version worked for me, because my computer (user) made it, so technically it is not an "unknown app or program from the internet" so SmartScreen wouldn't bother. But your file triggers SmartScreen.

In the end, I guess there is no easy way to circumvent this problem as it seems.

**Comment by aleab** [comment]
Yeah, there's definitely no way to trick SmartScreen!
I also tried a Windows utility program, *iexpress*, to create a self-extracting archive, but for some reason Windows Defender thinks the resulting installer is a trojan. 😕

Anyway, I'm gonna close this issue; if you come up with a solution, feel free to comment here.
