### ISSUE TITLE
Crash when using MouseWheel hotkeys

### ISSUE THREAD

**Issue by Aldarana** [aleab/toastify#60]
When assigning Mouse Wheel Up or Mouse Wheel Down as a hotkey Toastify will crash after saving the change. Toastify will continue to crash every time it is launched after that until the config file is deleted or the system is restarted. After a system restart the setting appears to be saved but doesn't seem to work.

Assigning MWheel UP/Down to any hotkey seems to cause the problem though I didn't test assigning MWheel Up/Down to disabled hotkeys.

Log File:
[Toastify.log](https://github.com/aleab/toastify/files/1866537/Toastify.log)

**Comment by aleab** [comment]
Unfortunately, some major change I've introduced in the last few days after adding that feature might have broke it. I should have tested everything again before releasing the update, I'm sorry. 😓

I'll look into it and probably release an hotfix in the following days.

**Comment by Vankog** [comment]
Can confirm this.
Disabling the Hotkey does work, though.

Unfortunately the Log does not provide any information about this.
The Windows Event viewer has some information:
It results into three subsequent crashes.
1. from .NET with a System.NullReferenceException
1. Application Error with unknonw module
1. Application Error in module: C:\Windows\System32\KERNELBASE.dll

**Comment by aleab** [comment]
@Vankog I reproduced this in Visual Studio. It's *"just"* a callback being made to a supposedly garbage collected delegate.
I'm currently reviewing every commit after c85dc52, to find out what broke it.

**Comment by Redtuzk** [comment]
@aleab All good, I'm just happy you implemented the feature I requested so quickly! :)

**Comment by aleab** [comment]
I just released an hotfix. It's fixed now.
