### ISSUE TITLE
full path of developer sources in log

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#61]
Just a minor issue that I just realized while checking the log:

## EXPECTED BEHAVIOUR
The log should not provide the full path of the developer PC's sources, but only the relative paths.

## ACTUAL BEHAVIOUR
Exceptions might show paths to sources on the developers PC. e.g. (see last line):

```c#
15:11:21,477+02:00 WARN  [Toastify.Core.Spotify.ConnectWithSpotify, 324] (5) – Unhandled WebException while connecting to Spotify.
System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at SpotifyAPI.Local.RemoteHandler.GetOAuthKey()
   at SpotifyAPI.Local.RemoteHandler.Init()
   at Toastify.Core.Spotify.ConnectWithSpotify(DoWorkEventArgs e) in E:\Users\Alessandro\Documents\Visual Studio 2017\Projects\toastify\Toastify\src\Core\Spotify.cs:line 324
```

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/1868150/Toastify.log)

**Comment by Vankog** [comment]
I see. Well it was just something I wanted you to be aware of. Because some people may say this is a security related issue. Some may say it is misleading for users or other devs.
But in my eyes it is nothing to be worried about.

**Comment by Vankog** [comment]
uh, just found something:
https://stackoverflow.com/questions/27952/how-do-i-change-the-locations-of-source-files-in-a-symbols-file-pdb

**Comment by aleab** [comment]
Yeah, that's a bit complicated.
The workaround does not keep the interesting part of the stack trace, though, that is the line numbers.

**Comment by thiagopromano** [comment]
Hey,
I made a Regex that substitutes from the user drive up to one of these "Spotify", "Toastify" to "..."

See if it helps 😉 
https://regexr.com/3o26g
