### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Edenost** [aleab/toastify#68]
After updating to v1.10.7 and then to v1.10.8 I receive the error 

Unhandled Exception.
Object reference not set to an instance of an object.

This is the log file: https://pastebin.com/X4mq2WRZ

**Comment by Edenost** [comment]
Toastify still works and I can change settings until I click OK on the Unhandled Exception.

**Comment by aleab** [comment]
Hi @Edenost, thanks for the report!
These random unexpected exceptions will most likely be fixed in the next release.
