### ISSUE TITLE
spotify not avaliable

### ISSUE THREAD

**Issue by claudiopj** [aleab/toastify#70]
Hi, 

I'm having trouble setting up toastify. I configured the shortcuts but it is returning the message spotify not avaliable

Please, help me

**Comment by aleab** [comment]
Hi @claudiopj, I'll help you, don't worry.

Can you post here you latest log file Just drag and drop the file inside the test box, it'll upload it automatically. You can find the latest log file inside `C:\Users\{UserName}\AppData\Local\Toastify`.

**Comment by claudiopj** [comment]
Hi @aleab,

[Toastify.txt](https://github.com/aleab/toastify/files/1885161/Toastify.txt)
I have not found any logs in this folder. The only folder I found from toastify is inside the roaming folder and inside there is only one XML

Thank you for your help

**Comment by aleab** [comment]
As @Vankog said, please install the latest version. Version 1.8.3 is pretty old and doesn't work anymore.

**Comment by claudiopj** [comment]
It worked! Thank you so much for all your help. God bless you!!
