### ISSUE TITLE
Hotkey mappings issue

### ISSUE THREAD

**Issue by Capiz** [aleab/toastify#75]
If this is a crash, bug or unexpected behaviour report, please use the following template.

## EXPECTED BEHAVIOUR
![image](https://user-images.githubusercontent.com/2978236/40175507-9bd3457a-59d8-11e8-9ef6-3fb48bced898.png)
When i chose ex. SHIFT for Play, i would expect it to be chosen for Play, only.

## ACTUAL BEHAVIOUR
When i chose ex. SHIFT for Play, it chooses SHIFT for ALL other hotkeys.

## STEPS TO REPRODUCE THE BEHAVIOUR
It happens for ALL hotkeys.

## LOG FILE
Cannot do this, as 1.0.7 is not having this issue. :-/

**Comment by aleab** [comment]
Hi @Capiz.
Thanks for catching this bug. I'll release an hotfix soon.
