### ISSUE TITLE
Error message when Toastify attempts to open on Start up

### ISSUE THREAD

**Issue by Element-OP** [aleab/toastify#84]
## EXPECTED BEHAVIOUR
Spotify and Toastify opening on Start up

## ACTUAL BEHAVIOUR
Spotify opening, but an error message from Toastify showing:
![image](https://user-images.githubusercontent.com/42191632/43808911-6ac1d85a-9aee-11e8-9007-457e7ec2408f.png)

## STEPS TO REPRODUCE THE BEHAVIOUR
Not sure :/

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/2268445/Toastify.log)

**Comment by Vankog** [comment]
Toastify is currently out of service, because of breaking changes on Spotify's side.

A major rewrite is needed to make it work again.

**Comment by aleab** [comment]
As @Vankog said, Toastify is unfortunately out of service currently. Subscribe to issue #86 to get notifications about any further update.

**Comment by Element-OP** [comment]
Sorry, I missed Vankog's post, but I'll stay tuned for further updates.
Thanks heaps for replying so soon!

On 9 Aug 2018 9:05 am, "Alessandro Attard Barbini" <notifications@github.com>
wrote:

As @Vankog <https://github.com/Vankog> said, Toastify is unfortunately out
of service currently. Subscribe to issue #86
<https://github.com/aleab/toastify/issues/86> to get notifications about
any further update.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aleab/toastify/issues/84#issuecomment-411587692>, or mute
the thread
