### ISSUE TITLE
Which proxy details do I use?

### ISSUE THREAD

**Issue by juliusdeblaaij** [aleab/toastify#87]
Hi there, when trying to start Toastify it displays this message:
![image](https://user-images.githubusercontent.com/16763204/43919999-fff1ba74-9c17-11e8-9924-32186f055474.png)
I have ProtonVPN installed which would maybe cause the problem (it`s turned off though).
Which settings do I use?
Host: IPV4 address,
but which username and password to use, my router's credentials don't seem to work?
Thanks

**Comment by aleab** [comment]
Doesn't matter actually, since Toastify doesn't currently work because of recent changes on Spotify's side.
Check out #86.

**Comment by juliusdeblaaij** [comment]
With the release of v1.10.9 and the current release of Spotify (1.0.87.*) this issue is now resolved.
