### ISSUE TITLE
Font-Color?

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#9]
Hey,

when utilizing transparency I have some issues reading the title:
![taost](https://user-images.githubusercontent.com/3804909/30031527-2c4e39d0-9192-11e7-8ac0-7aad370801ee.png)

I tried to do it for myself, but a quick glance at the code (via the website) did not gave me any clues about where to find it.

Generally I was thinking about a color chooser in the long run as well as a font-size setting, but I'm not a C# dev. So a quick fix should do the trick as well. Dropshadow, bigger font, more contrast color or something like this.

**Comment by aleab** [comment]
This is definitely on my list of things to do!
Will probably be in the next release; it might take a while, though – I'll be kinda busy in the next weeks/month.
In the meanwhile, if you want to do it yourself, the file you have to look at is [this](https://github.com/aleab/toastify/blob/master/Toastify/src/View/ToastView.xaml), specifically lines 51-56.

**Comment by Vankog** [comment]
Oh, now I see why I couldn't find it in there. The line was too long for me to see. Didn't realize for quite a while that the lines are much longer than the view suggests. ^^
OK, I guess for a quick fix this would take more effort to setup a proper .NET dev environment than I could currently spare. Maybe next year I can wrap my head around .NET.

**Comment by aleab** [comment]
Done!
Text color, shadow and font size can now be customized in the [new release](https://github.com/aleab/toastify/releases/latest).

**Comment by Vankog** [comment]
uhh , awesome!
