### ISSUE TITLE
Wont connect to Spotify, requests me to input a proxy

### ISSUE THREAD

**Issue by ViridianImpact** [aleab/toastify#90]
If this is a crash, bug or unexpected behaviour report, please use the following template.

## EXPECTED BEHAVIOUR
launch Toastify and use.

## ACTUAL BEHAVIOUR
after 2 minutes closes with the error
![toastify error](https://user-images.githubusercontent.com/31230393/44055706-0b411862-9efb-11e8-9775-719d93e8ea6c.PNG)

## STEPS TO REPRODUCE THE BEHAVIOUR
Happens every launch

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/2284609/Toastify.log)

**Comment by aleab** [comment]
Hi @ViridianImpact!

You are using an old version of Toastify, which doesn't work anymore (see #86 for details).
Download the newest release [here](https://github.com/aleab/toastify/releases/tag/v1.10.9).
