### ISSUE TITLE
Verified new Trojan found in version 1.10.9!

### ISSUE THREAD

**Issue by Geestarraw** [aleab/toastify#91]
I got a warning from my Norton Antivirus about version 1.10.9. I've sent the binary file to them for analyzation and got a confirmation back to them that there is a Trojan in the package.

I previously got a warning with version 1.10.8 but that turned out to be a false positive and Norton flagged after analyzation that file as OK. Version 1.10.9 is however not!

Here is the mail from Norton:

This message is an automatically generated reply -- do not reply to this message. This system is designed to analyze and process suspicious file submissions into Symantec Security Response and cannot accept correspondence or inquiries.

Submission Date 	2018-08-27 05:48:51
Tracking # 	42675410
Submitter 	<MY NAME>
Customer Notes 	Tracking number: 106325 This is the second time I get a warning for this GIT project (https://github.com/aleab/toastify/releases). However I think the virus error was different this time compared to version 1.10.8 that I supplied last time.

<MY NAME>,
We have processed your submission (Tracking #42675410) and your submission is now closed. The following is a report of our findings for the files in your submission:
Submission Summary
Protection available in Rapid Release Sequence Number: 195282 or greater.
Email Security .cloud Customers are protected within 2 hours of this latest definition.

Links:

    The latest Rapid Release definitions are available here . (ftp://ftp.symantec.com/AVDEFS/norton_antivirus/rapidrelease)
    To check the current sequence number of the Rapid Release definitions click here . (http://www.symantec.com/business/security_response/definitions/rapidrelease/index.jsp)
    More information on Rapid release definitions can be found here . (http://www.symantec.com/docs/TECH103326)

Files Submitted
# 	Filename 	MD5 	Determination 	Signature Protection Name 	RR Seq#
1 	Toastify 1.10.9.exe 	7c9caea6b009a8761116c94152236814 	New Threat 	Trojan Horse
	195282

Developer Notes:

1. Toastify 1.10.9.exe is a non-repairable threat.
Assessment
File 1: 	Toastify 1.10.9.exe
MD5: 	7c9caea6b009a8761116c94152236814
SHA256: 	c662b6e8d9376771c15fbf7a01d5d0dccd98f1d49b6d7cbfec9d73c8efaddee7
Determination: 	New Threat
Submission Detail: 	This file is detected as Trojan Horse with our existing Rapid Release definition set. Protection is available in Rapid Release definitions with a sequence number of 195282 or greater.
Signature Protection Name: 	Trojan Horse
Rapid Release Sequence Number: 	195282
This message was generated by Symantec Security Response automation.

More information on Threat Artifact determinations can be found in the article: What is a Threat Artifact?

Should you have any questions about your submission, please contact our regional technical support from the Symantec Web site and give them the tracking number included in this message.

Symantec Technical Support
http://support.symantec.com

Sincerely,
Symantec Security Response

**Comment by aleab** [comment]
Analysis reports from VirusTotal:
* [ToastifyInstaller.exe](https://www.virustotal.com/#/file/c662b6e8d9376771c15fbf7a01d5d0dccd98f1d49b6d7cbfec9d73c8efaddee7/detection)
* [Toastify.exe](https://www.virustotal.com/#/file/0867d87f114616e62b3895b4b52ece653b96cb2be1495fbbb28229f66199ee52/detection)
* [ToastifyAPI.dll](https://www.virustotal.com/#/file/9ec4a792b2d44f1a815b56d80f606fae47e46b9423137b5bff4e71540951aab0/detection)

The *"Verified new Trojan found in version 1.10.9!"* is definitely a false positive to my knowledge, presumably caused by NSIS (which is why only the installer triggers the antivirus).

Toastify's source code is entirely available in this repository; if you think it contains malicious code, you can check it out or have someone do that for you. If you think the installers I uploaded in the release page are infected, you can build your own version from the source code or have someone do that for you.

You can check out exactly what changed from version 1.10.8 to version 1.10.9 by comparing the respective tags of this repository. (https://github.com/aleab/toastify/compare/v1.10.8...aleab:v1.10.9)

**Comment by Geestarraw** [comment]
I'm a developer myself and I read enough code at and outside of office and don't have any time going through your source code as well. :)

I'm not reporting this issue to mess with you. But if a big antivirus company like Symantec analyzes a file in their sandbox environments and finds a new threat adding it to their hash algorithms 2 hours later I would take that seriously. I don't know if they will share this with VirusTotal or not but and if so they might signal it later.

Anyway - I report it because I use Toastify and liked I could continue to use it after the original developer stopped maintaining it which is why I love this branch. I put the effort to manually go to Nortons report page to have it analyzed after a first flag by Norton Antivirus as "I can't live without it". But I can't install a software Norton flags as a real threat even after analyzation.

If you're using any third party libraries or such that might be something to look into. If you still thinks its a false positive I would recommend trying to solve it with Symantec as I believe they have a big user base. As a developer I wouldn't like to have my software blacklisted by them. And personally I would love if you could solve it!

**Comment by aleab** [comment]
Unfortunately I don't have the will nor the time to find out what's causing this false positive with Norton and other antivirus softwares. It's most likely just the NSIS installer which is causing it, but I can't really be bothered trying to rewrite it using another installation system.

> But if a big antivirus company like Symantec analyzes a file in their sandbox environments and finds a new threat adding it to their hash algorithms 2 hours later I would take that seriously.

Symantec is undeniably big, but is also known for its huge amount of false positives, which makes it very very unreliable, in my opinion.
https://www.av-comparatives.org/tests/false-alarm-test-march-2018/
https://www.av-comparatives.org/tests/false-alarm-test-september-2017/

**Comment by Geestarraw** [comment]
I sent the file to the Norton whitelisting page and they have now changed their status. Even latest 1.10.12 works fine now without any warnings.
