### ISSUE TITLE
Invalid arguments

### ISSUE THREAD

**Issue by heamaral** [aleab/toastify#92]
Just updated to the latest version and I got the following error:
![error image](https://i.imgur.com/ZMsA90j.png)

**Comment by aleab** [comment]
Well, that's particularly odd!
I just tested the release build on my machine and it's the same. I tested the debug version like 10 minutes ago and there were no issues.

I'll look into it!

**Comment by aleab** [comment]
Found the (silly!) problem. I'll release an hotfix very soon.

**Comment by bartuszekj** [comment]
Same here. Thanks for taking care of it so quickly @aleab!

**Comment by aleab** [comment]
Done! Fixed in [v1.10.11](https://github.com/aleab/toastify/releases/tag/v1.10.11).
