### ISSUE TITLE
Directory not found after installing in windows7

### ISSUE THREAD

**Issue by heamaral** [aleab/toastify#95]
%LOCALAPPDATA%\Toastify folder should be created during install or initialization.

![](https://i.imgur.com/5Bcf6Fs.png)

**Comment by aleab** [comment]
I'm pretty sure the installer should take of that. I'll take a look later.
Thanks for all these bug reports! 👍

**Comment by aleab** [comment]
Fixed in the latest release: [v1.10.12](https://github.com/aleab/toastify/releases/tag/v1.10.12).
