### ISSUE TITLE
Unhandled exception pop up

### ISSUE THREAD

**Issue by xaarock** [aleab/toastify#98]
If this is a crash, bug or unexpected behaviour report, please use the following template.

## EXPECTED BEHAVIOUR
Music will change to next song whilst in fullscreen game

## ACTUAL BEHAVIOUR
Toastify crashed upon switch to next song, tabbed out of game "Unhandled exception"
## STEPS TO REPRODUCE THE BEHAVIOUR
Launch toastify and play music whilst playing a fullscreen game

## LOG FILE
*(Drag and drop your `Toastify.log` file here; it can be found in `%LocalAppData%\Toastify`)*
Can't find log file in appdata.

**Comment by aleab** [comment]
Hi @xaarock and thank you for the bug report!

Unfortunately, however, I couldn't reproduce your issue. I've tried a bunch of games (specifically, Mass Effect Andromeda, Dragon Age Inquisition, The Witcher 3, Divinity: Original Sin 2, Sid Meier's Civilization V, Quake Live), both in *"real"* fullscreen and borderless windowed fullscreen mode, and Toastify didn't crash upon changing song.

1. What game were you playing exactly?
2. Does it happen consistently or was it a one-off, isolated case?
3. Does it happen with every game or just with one/some in particular?
4. Can you look for a log file inside the installation directory of Toastify? It should be named `log.log` or something like that ending in `.log`; if it's there, upload it here, please.
5. If you can't find the log file mentioned above or if it's empty, the log file in AppData **must** exist. Look for a directory named `Toastify` in `C:\Users\<user-name>\AppData\Local\`; the log file is inside it.

**Comment by xaarock** [comment]
Note: The other games I play are all windowed fullscreen, I will test it with another fullscreen game.

**Comment by aleab** [comment]
That log file has been really helpful, thanks!
Can you check if this version of Toastify works now? [ToastifyInstaller.zip](https://github.com/aleab/toastify/files/2568388/ToastifyInstaller.zip)

I'll have to wait for a friend of mine to let me test it with his copy of CS:GO before actually releasing a new version, though.
